# Generated by Django 3.2.9 on 2022-05-19 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100, unique=True)),
                ('Precio', models.CharField(max_length=250)),
                ('Cantidad', models.IntegerField()),
                ('Descripción', models.CharField(max_length=250)),
            ],
        ),
    ]
