# Generated by Django 3.2.9 on 2022-06-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_vendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='CantidadVendida',
            field=models.IntegerField(default=0),
        ),
    ]
