# Generated by Django 3.2.9 on 2022-06-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_producto_cantidadvendida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='Precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='PrecioCompra',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='PrecioVenta',
            field=models.IntegerField(default=0),
        ),
    ]
