# Generated by Django 3.2.9 on 2022-06-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20220602_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='Ganancia',
            field=models.IntegerField(default=0),
        ),
    ]
